apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    hypervisorConfiguration:
      name: hyperv-layered
    developerConfiguration:
      featureGates:
      - HyperVLayered
      - ConfigurableHypervisor
    imagePullPolicy: Always
    obsoleteCPUModels:
      qemu64: false
      qemu64-1: false
  customizeComponents: {}
  imagePullPolicy: Always
  workloadUpdateStrategy: {}
