name: Wake up Azure VM

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string

jobs:
  wake-up-vm:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Wake up Azure VM
        uses: azure/vm@v1
        with:
          name: ${{ vars.COMPUTE_NAME }}
          resource-group: ${{ vars.RESOURCE_GROUP }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}
          action: start
